import {
  Bath,
  Waves,
  Umbrella,
  Coffee,
  UtensilsCrossed,
  ConciergeBell,
  Dumbbell,
  Baby,
  Plane,
  Eye,
  Building2,
  Flame,
  Snowflake,
  Dice5,
  DoorOpen,
  type LucideIcon,
} from "lucide-react";

export const AMENITY_META: Record<string, { label: string; icon: LucideIcon }> = {
  spa: { label: "Spa", icon: Bath },
  pool: { label: "Pool", icon: Waves },
  beachfront: { label: "Beachfront", icon: Umbrella },
  breakfast: { label: "Breakfast", icon: Coffee },
  michelin: { label: "Fine dining", icon: UtensilsCrossed },
  butler: { label: "Butler", icon: ConciergeBell },
  gym: { label: "Fitness", icon: Dumbbell },
  kidsclub: { label: "Kids' club", icon: Baby },
  airporttransfer: { label: "Transfers", icon: Plane },
  oceanview: { label: "Ocean view", icon: Eye },
  rooftop: { label: "Rooftop", icon: Building2 },
  fireplace: { label: "Fireplace", icon: Flame },
  ski: { label: "Ski-in/out", icon: Snowflake },
  casino: { label: "Casino", icon: Dice5 },
  connecting: { label: "Connecting", icon: DoorOpen },
};
